# Generated by Django 6.0.6 on 2026-08-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driver_remove_driverprofile_user_remove_vehicle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_requests', to='accounts.coupon'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='end_location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='estimated_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='requested_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='requested_vehicle_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='start_location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
