# Generated by Django 6.0.6 on 2026-08-18 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_driver_status_riderequest_end_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='dropoff',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='accounts.driver'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='accounts.vehicle'),
        ),
    ]
