# Generated by Django 6.1 on 2026-08-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ride_status_alter_ride_driver_alter_ride_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='dropoff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
