# Generated by Django 6.0.6 on 2026-08-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_driver_wallet_balance_payment_commission_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='shared_passengers',
        ),
    ]
