# Generated by Django 6.0.6 on 2026-09-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_passenger_shared_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='earnings',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='wallet_balance',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='commission_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='driver_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tran_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='val_id',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='passenger',
            name='shared_passengers',
            field=models.ManyToManyField(blank=True, related_name='shared_with', to='accounts.passenger'),
        ),
        migrations.DeleteModel(
            name='DriverWalletTransaction',
        ),
    ]
