# Generated by Django 6.0.6 on 2026-09-16 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_riderequest_dropoff'),
        ('accounts', '0007_remove_passenger_shared_passengers'),
    ]

    operations = [
    ]
