# Generated by Django 6.0.6 on 2026-09-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_driver_earnings_remove_driver_wallet_balance_and_more'),
        ('accounts', '0009_add_review_trigger'),
    ]

    operations = [
    ]
