# Generated by Django 6.0.6 on 2026-09-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20260917_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='category_target',
            field=models.CharField(choices=[('ALL', 'All Passengers'), ('VIP', 'VIP Passengers'), ('REGULAR', 'Regular Passengers'), ('NEWBIE', 'Newbie Passengers')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Max discount limit in BDT (0 for no cap)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g. 20.00 for 20%)', max_digits=5),
        ),
    ]
